### ISSUE TITLE
AspectJ & Retrolambda & AndroidAnnotations & MultiDex

### ISSUE THREAD

**Issue by Archinamon** [leolin310148/GradleAndroidAspectJPlugin#1]
Hello!

Is there's a solution or tweak to make this plugin friendly with MultiDex?
Without AJ everything is good. My error is:

Execution failed for task ':app:createDebugMainDexClassList'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_20\bin\java.exe'' finished with non-zero exit value 1

I'm appreciate any ideas and minds, thanks!

**Comment by leolin310148** [comment]
I'll try to support multiDex

**Comment by leolin310148** [comment]
@Archinamon 
I tested with AndroidAnnotations + MultiDex + Retrolambda and it works fine.
Here's the [Sample](https://github.com/leolin310148/GradleAndroidAspectJPlugin/tree/master/SampleApp-RetrolambdaMuitiDexAndroidAnnotations)
Can you provide me more information for that error?

**Comment by Archinamon** [comment]
Now trying to make the proj looking on your sample's plugins order.
What jdk for the sample are you using?
I set 1.8 and marked all modules to use 1.7 or 1.6, but :app uses 1.8

**Comment by Archinamon** [comment]
No luck. My error:

:app:compileRetrolambdaDebug
:app:copyDebugClasses
:app:compileDebugAspectJ
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:collectDebugMultiDexComponents
:app:packageAllDebugClassesForMultiDex
:app:shrinkDebugMultiDexComponents
:app:createDebugMainDexClassList FAILED
FAILURE: Build failed with an exception.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:createDebugMainDexClassList'.

My build.gradle is:
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        maven { url uri('../repo') }
    }

```
dependencies {
    //Fabric Crashlytics
    classpath 'io.fabric.tools:gradle:1.+'
    //retrolambda
    classpath 'me.tatarka:gradle-retrolambda:3.1.0'
    //aspectj
    classpath 'me.leolin:android-aspectj-plugin:1.0.+'
}
```

}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'me.leolin.gradle-android-aspectj'
apply plugin: 'io.fabric'

def AAVersion = '3.3.1'

retrolambda {
    defaultMethods true
    jdk System.getenv("JAVA_HOME")
    oldJdk System.getenv("JAVA7_HOME")
    javaVersion JavaVersion.VERSION_1_6
    exclude 'androidTest'
}

apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName android.defaultConfig.applicationId
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
    flatDir {
        dirs 'libs'
    }
}

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

```
defaultConfig {
    applicationId "org.fxclub.libertex"
    minSdkVersion 14
    targetSdkVersion 22
    multiDexEnabled true
    versionCode extractVersionCode();
    versionName "1.0.1"
}

buildTypes {
    debug {
        minifyEnabled false
    }
    release {
        signingConfig signingConfigs.release;

        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        ext.betaDistributionGroupAliases = "my-testers"
    }
}

packagingOptions {
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
    exclude 'META-INF/notice.txt'
    exclude 'META-INF/license.txt'
}

lintOptions {
    abortOnError false
}

compileOptions {
    encoding = "UTF-8"
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

}

dependencies {
    compile 'com.android.support:multidex:1.0.1'

```
apt "org.androidannotations:androidannotations:$AAVersion"
compile "org.androidannotations:androidannotations-api:$AAVersion"

compile fileTree(include: ['*.jar'], dir: 'libs')
compile (name:'stockchart-release', ext:'aar')
compile (name:'stockchartpro-release', ext:'aar')

compile project(':retrostream')
compile project(':libraries:retrofit-fork')
compile project(':libraries:comboseekbar')
compile project(':libraries:spinnerwheel')
compile(project(':libraries:viewpagerindicator')) {
    exclude(group: 'com.android.support', module: 'support-v4')
}
compile('com.octo.android.robospice:robospice-retrofit:1.4.14') {
    exclude(group: 'com.squareup.retrofit', module: 'retrofit')
}
compile('com.google.apis:google-api-services-analytics:v3-rev99-1.19.0') {
    exclude(group: 'org.apache.httpcomponents', module: 'httpclient')
}
compile 'org.jetbrains:annotations:+@jar'
compile 'com.android.support:appcompat-v7:22.1.1'
compile 'de.greenrobot:eventbus:2.4.0'
compile 'com.jeremyfeinstein.slidingmenu:library:1.3@aar'
compile 'com.crittercism:crittercism-android-agent:4.5.3'
compile 'com.github.oxo42:stateless4j:2.4.2'
compile('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
    exclude group: 'com.google.android', module: 'support-v4'
}
compile 'com.daimajia.swipelayout:library:1.1.7@aar'
compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
compile 'com.j256.ormlite:ormlite-android:4.45'
compile('com.crashlytics.sdk.android:crashlytics:2.2.1@aar') {
    transitive = true;
}
```

}

And settings.gradle:
include ':app'
include ':retrostream'
include ':libraries:retrofit-fork'
include ':libraries:comboseekbar'
include ':libraries:spinnerwheel'
include ':libraries:viewpagerindicator'

**Comment by Archinamon** [comment]
I've got this crash trying to launch SampleApp-RetrolambdaMuitiDexAndroidAnnotations.

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "me.leolin.sample.combine.app.MainActivity_" on path: DexPathList[[zip file "/data/app/me.leolin.sample.combine.app-2.apk", zip file "/data/data/me.leolin.sample.combine.app/code_cache/secondary-dexes/me.leolin.sample.combine.app-2.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/me.leolin.sample.combine.app-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
```

**Comment by leolin310148** [comment]
@Archinamon 
I cannot reproduce your problem.
I think the 'java.lang.ClassNotFoundException' is not a problem from aspectj,
I got the Exception sometimes and after I do 'clean' and 'assemble' again it works fine.

**Comment by Archinamon** [comment]
Found, that in my case MultiDex replaces preDex task and filterDebugPreDex task doesn't execute at all.
Trying to modify the plugin. There should be, possible, a bit different workaround for multiDex tasks.

**Comment by Archinamon** [comment]
I've re-wrote plugin, taken uPhyca's plugin as base and some your code to support correct compile steps. Now it works brilliant and even supports .aj files in native aspect language. :)

**Comment by leolin310148** [comment]
@Archinamon 
Can you share your code?

**Comment by Archinamon** [comment]
Sure. I've just pushed it onto my repo.
https://github.com/Archinamon/GradleAspectJ-Android
