### ISSUE TITLE
Doesn't work with library project

### ISSUE THREAD

**Issue by jd-alexander** [leolin310148/GradleAndroidAspectJPlugin#2]
Your readme states that this library works with library projects but it's not working the way I would want it. 
Your library example involves pointcuts targetting methods that exist within the library itself. What I want to achieve is functionality that allows the library to be used as a dependency for other apps. When I tried it in that fashion my advice isn't being triggered. I guess the app that has it as a dependency isn't beaving woven by Aspect J or something along those lines.

**Comment by leolin310148** [comment]
Yes, library project is currently not support to weaving other project.
I'll try to make it possible, and you can use jar like my SampleJarLib to weaving your main app now.

**Comment by jd-alexander** [comment]
I will have to wait until its implemented because I want to release my project as aar. Alot of people want this feature so if your library does it it would really standout from all the others. This popular project uses Aspect J and seems to work well as a library https://github.com/JakeWharton/hugo

**Comment by jd-alexander** [comment]
I follow the example from the library above and made a groovy plugin that adds my library as a dependency to the project before running the aspectj tasks. Here's my project https://github.com/jd-alexander/flender

**Comment by Archinamon** [comment]
In my mind the only way to achieve this functionality is to make needed gradle tasks providing by the lib and call these tasks from the main module instead of main's. But this not modulable and looks like a small framework, not a lib. Much simpler and correct way is to apply AspectJ plugin on the main module itself.
